repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        language: system
        entry: isort
        require_serial: true
        types: [python]
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        require_serial: true
        types: [python]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        language: system
        entry: flake8
        require_serial: true
        types: [python]